import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import NavBar from "@/app/ui/nav-bar";
import NavBarUser from "@/app/ui/nav-bar-user";
import {auth} from "@/auth";

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Ambassadors FI MU',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const session = await auth();

  return (
    <html lang="en">
      <body className={inter.className}>
        {session ? <NavBarUser></NavBarUser> : <NavBar></NavBar>}
        {/*<NavBar></NavBar>*/}
        {/*<NavBarUser></NavBarUser>*/}

        {children}
      </body>
    </html>
  )
}
