@startuml
'https://plantuml.com/use-case-diagram

rectangle System {
  usecase "Register" as register
  usecase "Log in" as login
  
  usecase "View events" as events
  usecase "View their events" as their
  usecase "View event history" as hist

  usecase "Create a new event suggestion" as newSuggestion
  usecase "Create a report from event" as report
  usecase "Sign up for an event" as signUp

  (report) .> (signUp) : extend
  usecase "View approved reports" as oldReports

  (events) ..> (their) : include
  (events) ..> (hist) : include
  (hist) .> (oldReports) : include

  package "Personal Info And Preferences" as pers {
    usecase "View personal info" as viewSelfInfo
    usecase "Change personal info" as changeSelfInfo
    usecase "Change email" as changeSelfEmail
    usecase "Change phone number" as changeSelfNumber
    usecase "Set notifications preferences" as changeNotif

    (changeSelfInfo) ..> (changeSelfEmail) : include
    (changeSelfInfo) ..> (changeSelfNumber) : include
  }

  package "Programme info" as infoPanel {
    usecase "View programme info" as info
    usecase "View contact information of management" as infoMan
  }

  usecase "Approve ambassador"
}

left to right direction
actor "Unregistered visitor" as vi
vi -> register
'vi ---> infoMan
vi ---> infoPanel

left to right direction
actor Ambassador as am

vi <|--am

am ---> events
'am --> infoPanel
'am --> infoMan
am --> login
am ---> newSuggestion
'am --> report
am --> pers
am ----> signUp

actor Manager as man
'info <---man
pers <--- man
infoPanel <--- man

@enduml